# Generated by Django 2.0.6 on 2018-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('stop_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stop_id_long', models.CharField(max_length=200)),
            ],
        ),
    ]
