# Generated by Django 2.0.6 on 2018-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0002_stopsv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('description', models.TextField()),
                ('mainDescription', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('cloudiness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='forecast_weather',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('description', models.TextField()),
                ('mainDescription', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('cloudiness', models.FloatField()),
            ],
        ),
    ]
