# Generated by Django 2.0.6 on 2018-06-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0009_forecast_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_weather',
        ),
    ]
