# Generated by Django 2.0.6 on 2018-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0011_current_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('stop_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stop_id_long', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='current_weather',
        ),
        migrations.DeleteModel(
            name='forecast_weather',
        ),
    ]
