# Generated by Django 2.0.6 on 2018-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0012_auto_20180629_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stops',
        ),
    ]
