# Generated by Django 2.0.6 on 2018-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0013_delete_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_weather',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('dt', models.FloatField()),
                ('temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('description', models.TextField()),
                ('mainDescription', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('cloudiness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='forecast_weather',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('description', models.TextField()),
                ('mainDescription', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
