# Generated by Django 2.0.6 on 2018-06-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0016_current_weather_forecast_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forecast_weather',
        ),
    ]
