# Generated by Django 2.0.6 on 2018-06-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0020_delete_forecast_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forecast',
        ),
    ]
