# Generated by Django 2.0.6 on 2018-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0022_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopsv5',
            fields=[
                ('stop_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('stop_name_short', models.TextField()),
                ('longitude', models.FloatField()),
                ('stop_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip_avg',
            fields=[
                ('index_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_stop', models.TextField()),
                ('end_stop', models.TextField()),
                ('hour', models.FloatField()),
                ('minute', models.FloatField()),
                ('day_of_week', models.FloatField()),
                ('avg_time_taken', models.FloatField()),
                ('avg_hang', models.FloatField()),
            ],
        ),
    ]
